Add markdown linter hook
mineiros-io/pre-commit-hooks pull request #11
Opened 2020-05-26 14:16 UTC by soerenmartius

2020-05-26 22:44 UTC, mariux requested changes
I don't think this makes much sense .. as we have tons of private GitHub repositories where this will fail all the time..

2020-05-26 22:44 UTC, mariux commented on README.md
> +          npm install -g markdown-link-check                                                                                                           c
What is this c?

2020-05-27 05:51 UTC, soerenmartius commented on README.md
> +          npm install -g markdown-link-check                                                                                                           c
resolved in 0d26bb9

2020-05-27 05:58 UTC, soerenmartius commented
> I don't think this makes much sense .. as we have tons of private GitHub repositories where this will fail all the time.

I don't agree. First of all, we provide a hook that can be used for checking links for validity in markdown. This doesn't mean that you need to use though. Second, if you run pre-commit on a private repository, you already have access to that repository. This is a hook that should be used by us when developing modules, nothing else.

I think it's very useful taking into consideration, that we can also configure it properly and exclude patterns such as `/github/` ( I still need to add an option for that to the shellscript though ).

2020-05-27 07:03 UTC, mariux approved these changes
lgtm

2020-05-27 07:04 UTC, merged