feat: add terradoc
mineiros-io/pre-commit-hooks pull request #29
Opened 2022-03-28 14:40 UTC by thiesen

2022-03-28 15:36 UTC, thiesen commented
[ch5155]

2022-03-31 13:49 UTC, soerenmartius requested changes
Good job thank you, just a small change requests from my end

2022-03-31 13:49 UTC, soerenmartius commented on pre_commit_hooks/terradoc/fmt.sh
> +terradoc fmt $1 -w
Can we have a guard here to ensure terradoc is installed? eg https://github.com/mineiros-io/pre-commit-hooks/blob/master/pre_commit_hooks/markdown/markdown-link-check.sh#L5

2022-03-31 19:42 UTC, soerenmartius approved these changes
lgtm! Thank you!

2022-04-01 09:42 UTC, soerenmartius commented
@mariux could you give this is another review please?

2022-04-05 20:28 UTC, merged